### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by ptoews** [EmperorCookie/accapi#7]
Above exception is thrown in the following line, just after starting the wrapper with the game running and a session opened:

https://github.com/EmperorCookie/accapi/blob/f93040b4b8ae30f569efadfe4e29ce9761155a9d/src/accapi/client.py#L103

Here is the traceback:
```
Traceback (most recent call last):
  File "D:\Development\accapi\src\accapi\client.py", line 417, in _run
    self._receiveMethods[messageType]()
  File "D:\Development\accapi\src\accapi\client.py", line 263, in _receive_registration_result
    result = RegistrationResult.receive(self._receive)
  File "D:\Development\accapi\src\accapi\structs.py", line 34, in receive
    return cls(*cls.receive_args(receiveMethod))
  File "D:\Development\accapi\src\accapi\structs.py", line 38, in receive_args
    args = receiveMethod("i??s")
  File "D:\Development\accapi\src\accapi\client.py", line 258, in _receive
    val, = struct.unpack(f"{self.endianess}{f}", self._reader.read(struct.calcsize(f)))
  File "D:\Development\accapi\src\accapi\client.py", line 103, in read
    return data
UnboundLocalError: local variable 'data' referenced before assignment
```

It seems the ifs above are not exhaustive, however I do not fully understand the code in that method yet. Probably a quick fix for you, otherwise I will investigate it further tomorrow.

**Comment by ptoews** [comment]
Just FYI, I tried defaulting `data = None` in that method as a quick fix, which caused a different exception:

```
Traceback (most recent call last):
  File "D:\Development\accapi\src\accapi\client.py", line 418, in _run
    self._receiveMethods[messageType]()
  File "D:\Development\accapi\src\accapi\client.py", line 264, in _receive_registration_result
    result = RegistrationResult.receive(self._receive)
  File "D:\Development\accapi\src\accapi\structs.py", line 34, in receive
    return cls(*cls.receive_args(receiveMethod))
  File "D:\Development\accapi\src\accapi\structs.py", line 38, in receive_args
    args = receiveMethod("i??s")
  File "D:\Development\accapi\src\accapi\client.py", line 259, in _receive
    val, = struct.unpack(f"{self.endianess}{f}", self._reader.read(struct.calcsize(f)))
TypeError: a bytes-like object is required, not 'NoneType'
```
This might be a different issue or not one at all though.

**Comment by EmperorCookie** [comment]
~~I think you might have missed a pull, I did sneak a change in there to address this exact problem, see 90df5fe.~~

My mistake, looks like I wasn't on `master` when I did the tests. I will quickly fix.

**Comment by EmperorCookie** [comment]
TODO: Add tests to this repo.
